[project]
name = "be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.115.14",
    "uvicorn[standard]==0.34.3",
]

[dependency-groups]
dev = [
    "pre-commit==4.2.0",
    "ruff>=0.12.1",
]
